#!/bin/bash
# 自动化1：私有仓库备份
# 暂存变更 → 生成语义提交信息 → 推送 GitHub → 失败告警

set -e

WORKSPACE="/Users/liam/.openclaw/workspace"
cd "$WORKSPACE"

GIT_STATUS=$(git status --porcelain 2>&1)
if [ -z "$GIT_STATUS" ]; then
  echo "[备份] 无变更，跳过"
  exit 0
fi

echo "[备份] 检测到变更，开始暂存..."

# 生成语义化提交信息
COMMIT_MSG=$(cat << 'EOF'
chore: daily workspace backup

- Auto-generated by OpenClaw cron
EOF
)

# 添加所有变更
git add -A

# 验证暂存内容
STAGED=$(git diff --cached --name-only)
if [ -z "$STAGED" ]; then
  echo "[备份] 暂存内容为空，跳过"
  exit 0
fi

echo "[备份] 变更文件："
echo "$STAGED"

# 提交
git commit -m "$COMMIT_MSG"

# 推送（含重试）
MAX_RETRIES=3
for i in $(seq 1 $MAX_RETRIES); do
  echo "[备份] 推送尝试 $i/$MAX_RETRIES..."
  if git push 2>&1; then
    echo "[备份] 推送成功 ✓"
    exit 0
  fi
  echo "[备份] 推送失败，等待 5 秒..."
  sleep 5
done

echo "[备份] ❌ 推送失败（已重试 $MAX_RETRIES 次）"
exit 1
